import { ActionTypes } from 'pltr'
import Mixpanel from 'react-native-mixpanel'

const { ADD_CHARACTER, ADD_TAG, ADD_PLACE, ADD_CARD,
  ADD_LINE, ADD_SCENE, ADD_NOTE, ADD_CHARACTER_ATTRIBUTE, ADD_PLACES_ATTRIBUTE,
  ATTACH_CHARACTER_TO_CARD, ATTACH_PLACE_TO_CARD, ATTACH_TAG_TO_CARD,
  ATTACH_CHARACTER_TO_NOTE, ATTACH_PLACE_TO_NOTE, ATTACH_TAG_TO_NOTE } = ActionTypes
const WHITELIST = [ADD_CHARACTER, ADD_TAG, ADD_PLACE, ADD_CARD,
  ADD_LINE, ADD_SCENE, ADD_NOTE, ADD_CHARACTER_ATTRIBUTE, ADD_PLACES_ATTRIBUTE,
  ATTACH_CHARACTER_TO_CARD, ATTACH_PLACE_TO_CARD, ATTACH_TAG_TO_CARD,
  ATTACH_CHARACTER_TO_NOTE, ATTACH_PLACE_TO_NOTE, ATTACH_TAG_TO_NOTE]

const tracker = store => next => action => {
  if (WHITELIST.includes(action.type)) {
    Mixpanel.track(action.type.toLowerCase())
  }
  return next(action)
}

export default tracker
